FROM python:3.12-slim

WORKDIR /app

# Копіюємо весь app (скрипти, шаблони, static)
COPY app/ ./ 

# Встановлюємо залежності
RUN pip install --no-cache-dir flask cryptography

EXPOSE 5000

CMD ["python", "app.py"]
